/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ContactMe: typeof import('./src/components/ContactMe.vue')['default']
    DateTime: typeof import('./src/components/DateTime.vue')['default']
    MainContent: typeof import('./src/components/MainContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollDown: typeof import('./src/components/ScrollDown.vue')['default']
    ScrollToTop: typeof import('./src/components/ScrollToTop.vue')['default']
    SocialItem: typeof import('./src/components/SocialItem.vue')['default']
    Socials: typeof import('./src/components/Socials.vue')['default']
    WorkItem: typeof import('./src/components/WorkItem.vue')['default']
    Works: typeof import('./src/components/Works.vue')['default']
  }
}
