// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    CardContainer: typeof import('./src/components/CardContainer.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Offcanvas: typeof import('./src/components/Offcanvas.vue')['default']
    Projects: typeof import('./src/components/Projects.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillItem: typeof import('./src/components/SkillItem.vue')['default']
    Skills: typeof import('./src/components/Skills.vue')['default']
    Wrapper: typeof import('./src/components/Wrapper.vue')['default']
  }
}

export {}
